version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/frontend-app
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000

  backend:
    build:
      context: ./backend/backend-api
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
