apiVersion: v1
kind: Service
metadata:
  name: governance-validator
  namespace: governance-system
spec:
  selector:
    app: governance-validator
  ports:
  - port: 443
    targetPort: 8443
  type: ClusterIP
