name: Functional Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies for frontend
        run: |
          cd frontend/frontend-app
          npm ci
          
      - name: Install dependencies for backend
        run: |
          cd backend/backend-api
          pip install poetry
          poetry install
          
      - name: Start backend service
        run: |
          cd backend/backend-api
          poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          sleep 5
          
      - name: Build and start frontend
        run: |
          cd frontend/frontend-app
          npm run build
          npm run preview &
          sleep 5
          
      - name: Install Playwright
        run: |
          cd e2e-tests
          npm ci
          npx playwright install --with-deps chromium
          
      - name: Run Playwright tests
        run: |
          cd e2e-tests
          SKIP_WEB_SERVER=true npm test
          
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: e2e-tests/playwright-report/
          
      - name: Upload test screenshots
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-screenshots
          path: e2e-tests/tests/screenshots/
